bootstrap.servers=127.0.0.1:9092
group.id=commerce-connect
config.storage.topic=commerce-connect-configs
offset.storage.topic=commerce-connect-offsets
status.storage.topic=commerce-connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.flush.interval.ms=1000
listeners=http://127.0.0.1:8083
rest.advertised.host.name=127.0.0.1
plugin.path=/opt/kafka/connect
